@startmindmap

* PartitionedRegion

** InternalCache
***_ interface
***_ injected

**  StatisticsClock
***_ interface
***_ injected

** ColocationLoggerFactory
***_ interface
***_ injected

** DiskRegionStats
***_ class
***_ new
*** StatisticsTypeFactoryImpl singleton
*** StatisticsDescriptor new
*** StatisticsType singleton factory
*** Statistics singleton factory

** Node new

** StoppableReentrantReadWriteLock new
*** ReentrantReadWriteLock new
*** StoppableReadWriteLock new
*** StoppableWriteLock new

** PartitionedRegionDataStore static factory

** PartitionedRegionConfigValidator new

** PartitionedRegionDataView new

** PartitionedRegionRedundancyTracker new

** PartitionedRegionStats new
*** StatisticsTypeFactoryImpl singleton
*** StatisticsDescriptor new
*** StatisticsType singleton factory
*** Statistics singleton factory

** PRHARedundancyProvider new
*** PersistentBucketRecoverer new
**** RegionStatus new
**** StartupStatus new
*** PartitionedRegionRabalanceOp new
*** OneTaskOnlyExecutor new

** PRPersistentConfig new

** ProfileListener new

** RegionAdvisor static factory

** RegionLogger class (pr calls static method(

** ScheduledExecutorService static method
*** LoggingThreadFactory new
*** ScheduledThreadPoolExecutor

** SenderIdMonitor

@endmindmap

