' vim: set tabstop=4 softtabstop=4 noexpandtab :
@startmindmap

title A Subset of PartitionedRegion Dependencies

* PartitionedRegion
	* //InternalCache//
		*_ injected

	* //StatisticsClock//
		*_ injected

	* //ColocationLoggerFactory//
		*_ injected

	* **DiskRegionStats**
		*_ new
		* **StatisticsTypeFactoryImpl**
			*_ static singleton
		* **StatisticsDescriptorImpl**
			*_ factory (static singleton)
		* **StatisticsTypeImpl**
			*_ factory (static singleton)
		* //Statistics//
			*_ factory (acquired via a method chain)

	* **Node**
		*_ new


	* **PartitionedRegionDataStore**
		*_ static implementation method

	* **PartitionedRegionConfigValidator**
		*_ new

	* **PartitionedRegionDataView**
		*_ new

	* **PartitionedRegionRedundancyTracker**
		*_ new

	* **PartitionedRegionStats**
		*_ new
		* **StatisticsTypeFactoryImpl**
			*_ static singleton
		* **StatisticsDescriptorImpl**
			*_ factory (static singleton)
		* **StatisticsTypeImpl**
			*_ factory (static singleton)
		* //Statistics//
			*_ factory (acquired via a method chain)

	* **PRHARedundancyProvider**
		*_ new
		* **PersistentBucketRecoverer**
			*_ new
			* **RegionStatus**
				*_ new
			* **StartupStatus**
				*_ new
		* **PartitionedRegionRabalanceOp**
			*_ new
			*_ many additional dependencies when it runs
		* **OneTaskOnlyExecutor**
			*_ new

	* **PRPersistentConfig**
		*_ new

	* **ProfileListener**
		*_ new

	* **RegionAdvisor**
		*_ static implementation method

	* **RegionLogger (Class)**
		*_ PartitionedRegion collaborates via static method

	* **ScheduledExecutorService**
		*_ static helper method
		* **LoggingThreadFactory**
			*_ new
		* **ScheduledThreadPoolExecutor**
			*_ new

	* **SenderIdMonitor**
		*_ static implementation method

	* **StoppableReentrantReadWriteLock**
		*_ new
		* **ReentrantReadWriteLock**
			*_ new
		* **StoppableReadWriteLock**
			*_ new
		* **StoppableWriteLock**
			*_ new

@endmindmap

